import type { LucideIcon } from "lucide-react";
import {
  AlarmClockCheck,
  ArrowLeftRight,
  Banknote,
  Blocks,
  Box,
  BriefcaseBusiness,
  Building2,
  CreditCard,
  Database,
  DollarSign,
  FolderCog,
  Gauge,
  LayoutDashboard,
  Package,
  Pencil,
  Receipt,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Store,
  Trash2,
  Truck,
  Users,
  UserCheck,
  UserX,
  Wallet,
  HandCoins,
  RotateCcw,
  PackagePlus,
  Eye,
  Printer,
  MapPin,
  UploadCloud,
} from "lucide-react";

export const iconMap = {
  dashboard: LayoutDashboard,
  mapPin: MapPin,
  view: Eye,
  print: Printer,
  upload: UploadCloud,
  inventory: Package,
  products: Box,
  edit: Pencil,
  categories: Blocks,
  brands: BriefcaseBusiness,
  stockOverview: Store,
  lowStock: AlarmClockCheck,
  alertRecords: ShieldCheck,
  stockMovements: ArrowLeftRight,
  transfers: Truck,
  sales: ShoppingCart,
  newSale: Receipt,
  soldItems: ShoppingBag,
  salesList: ScrollText,
  customers: Users,
  customerCredit: CreditCard,
  customerPayments: Wallet,
  purchases: ShoppingBag,
  newPurchase: Receipt,
  purchaseList: ScrollText,
  suppliers: Truck,
  supplierPayments: Banknote,
  accounts: Wallet,
  cashTransfers: ArrowLeftRight,
  expenses: DollarSign,
  reports: Gauge,
  assistant: Sparkles,
  demo: BriefcaseBusiness,
  admin: FolderCog,
  branches: Building2,
  settings: Settings,
  trash: Trash2,
  users: Users,
  userCheck: UserCheck,
  userX: UserX,
  roles: ShieldCheck,
  ledger: ScrollText,
  finance: Banknote,
  auditLogs: ScrollText,
  backups: Database,
  assign: PackagePlus,
  return: RotateCcw,
  collect: HandCoins,
  transfer: ArrowLeftRight,
  truck: Truck,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function getIcon(name: IconName) {
  return iconMap[name] || Settings;
}