export const APP_ROLES = [
  "ADMIN",
  "MANAGER",
  "SALES",
  "PURCHASE_ROLE",
  "SALES_ROLE",
  "STORE_ROLE",
  "STORE_STAFF",
  "WAREHOUSE_ROLE",
  "FINANCE_ROLE",
] as const;

export const APP_PERMISSION_DEFINITIONS = [
  { key: "location:view-all", label: "View all locations", group: "Locations", description: "Access stock, sales, purchases, and reports across every location." },
  { key: "location:multi", label: "Use multiple assigned locations", group: "Locations", description: "Switch between more than one assigned location without seeing every location globally." },
  { key: "dashboard:view", label: "View dashboard", group: "Dashboard", description: "Open the dashboard and profile workspace." },
  { key: "inventory:view", label: "View inventory", group: "Inventory", description: "View stock, movements, alerts, and inventory lists." },
  { key: "inventory:create", label: "Create inventory records", group: "Inventory", description: "Create items, categories, units, brands, and companies." },
  { key: "inventory:edit", label: "Edit inventory records", group: "Inventory", description: "Edit items, categories, units, brands, companies, and item settings." },
  { key: "inventory:delete", label: "Delete inventory", group: "Inventory", description: "Delete inventory records where deletion is allowed." },
  { key: "inventory:transfer", label: "Transfer inventory", group: "Inventory", description: "Create and manage stock transfers between locations." },
  { key: "inventory:adjust-prices", label: "Adjust item prices", group: "Inventory", description: "Apply bulk or location-specific selling price changes." },
  { key: "inventory:manage", label: "Manage inventory", group: "Inventory", description: "Compatibility umbrella for all inventory management permissions." },
  { key: "sales:create", label: "Create sales", group: "Sales", description: "Use POS, wholesale, and new sale entry." },
  { key: "sales:view", label: "View sales", group: "Sales", description: "View sales list, sold items, delivery orders, and sale details." },
  { key: "sales:edit", label: "Edit sales", group: "Sales", description: "Correct or update sales and sale line details." },
  { key: "sales:delete", label: "Delete sales", group: "Sales", description: "Delete or void sales where available." },
  { key: "sales.receipt.print", label: "Print sale receipts", group: "Sales", description: "Print sale receipt vouchers." },
  { key: "sales.receipt.export_pdf", label: "Export receipt PDF", group: "Sales", description: "Download sale receipt PDFs." },
  { key: "sales.receipt.export_excel", label: "Export receipt Excel", group: "Sales", description: "Download sale receipt spreadsheets." },
  { key: "sales.return.create", label: "Create sales returns", group: "Sales", description: "Create return or exchange records for completed sales." },
  { key: "sales.return.full", label: "Full sales returns", group: "Sales", description: "Return every remaining item on a sale." },
  { key: "sales.return.partial", label: "Partial sales returns", group: "Sales", description: "Return selected items from a sale." },
  { key: "sales.exchange.create", label: "Create sales exchanges", group: "Sales", description: "Exchange sold items for replacement items." },
  { key: "sales.return.approve", label: "Approve sales returns", group: "Sales", description: "Approve financial refund or collection adjustments for returns." },
  { key: "sales:deliveries", label: "Manage delivery orders", group: "Sales", description: "Create and update delivery order workflows." },
  { key: "sales:manage", label: "Manage sales", group: "Sales", description: "Compatibility umbrella for sale editing and delivery workflows." },
  { key: "customers:view", label: "View customers", group: "Customers", description: "View customers, customer balances, and customer credit." },
  { key: "customers:create", label: "Create customers", group: "Customers", description: "Create new customer records." },
  { key: "customers:edit", label: "Edit customers", group: "Customers", description: "Update customer records and contact details." },
  { key: "customers:delete", label: "Delete customers", group: "Customers", description: "Delete customers where deletion is allowed." },
  { key: "customers:manage", label: "Manage customers", group: "Customers", description: "Compatibility umbrella for customer create/edit/delete." },
  { key: "customer-payments:view", label: "View customer payments", group: "Customers", description: "View customer payment and settlement records." },
  { key: "customer-payments:create", label: "Create customer payments", group: "Customers", description: "Record customer payment and credit settlement entries." },
  { key: "purchases:create", label: "Create purchases", group: "Purchases", description: "Record new purchases and supplier payable entries." },
  { key: "purchases:view", label: "View purchases", group: "Purchases", description: "View purchase lists, details, and related purchase data." },
  { key: "purchases:edit", label: "Edit purchases", group: "Purchases", description: "Correct or update purchase records and line details." },
  { key: "purchases:delete", label: "Delete purchases", group: "Purchases", description: "Delete purchase records where deletion is allowed." },
  { key: "suppliers:view", label: "View suppliers", group: "Purchases", description: "View supplier lists and supplier balances." },
  { key: "suppliers:create", label: "Create suppliers", group: "Purchases", description: "Create new supplier records." },
  { key: "suppliers:edit", label: "Edit suppliers", group: "Purchases", description: "Update supplier records and contact details." },
  { key: "suppliers:delete", label: "Delete suppliers", group: "Purchases", description: "Delete suppliers where deletion is allowed." },
  { key: "suppliers:manage", label: "Manage suppliers", group: "Purchases", description: "Compatibility umbrella for supplier create/edit/delete." },
  { key: "supplier-payments:view", label: "View supplier payments", group: "Purchases", description: "View supplier payment records." },
  { key: "supplier-payments:create", label: "Create supplier payments", group: "Purchases", description: "Record supplier payment entries." },
  { key: "expenses:view", label: "View expenses", group: "Finance", description: "View expense records and expense pages." },
  { key: "expenses:create", label: "Create expenses", group: "Finance", description: "Record business expenses." },
  { key: "expenses:edit", label: "Edit expenses", group: "Finance", description: "Update expense records where editing is available." },
  { key: "expenses:delete", label: "Delete expenses", group: "Finance", description: "Delete expense records where deletion is allowed." },
  { key: "accounts:use", label: "Use accounts", group: "Finance", description: "Use cash and bank accounts in sales, purchases, and payments." },
  { key: "accounts:view", label: "View accounts", group: "Finance", description: "View finance accounts and balances." },
  { key: "accounts:create", label: "Create accounts", group: "Finance", description: "Create cash and bank accounts." },
  { key: "accounts:edit", label: "Edit accounts", group: "Finance", description: "Update cash and bank accounts." },
  { key: "accounts:delete", label: "Delete accounts", group: "Finance", description: "Delete accounts where deletion is allowed." },
  { key: "accounts:manage", label: "Manage accounts", group: "Finance", description: "Compatibility umbrella for account and cheque workflows." },
  { key: "cheques:view", label: "View cheques", group: "Finance", description: "View cheque registers and statuses." },
  { key: "cheques:manage", label: "Manage cheques", group: "Finance", description: "Update cheque status and cheque workflows." },
  { key: "ledger:view", label: "View ledger", group: "Finance", description: "View ledger and account movement reports." },
  { key: "cash-transfers:view", label: "View cash transfers", group: "Finance", description: "View cash transfer records." },
  { key: "cash-transfers:create", label: "Create cash transfers", group: "Finance", description: "Create transfers between cash and bank accounts." },
  { key: "cash-transfers:manage", label: "Manage cash transfers", group: "Finance", description: "Move funds between cash and bank accounts." },
  { key: "reports:view", label: "View reports", group: "Reports", description: "Open reports and export operational summaries." },
  { key: "ai:view", label: "Use AI insights", group: "Reports", description: "Ask operational questions and review AI recommendations." },
  { key: "demo:view", label: "View implementation demo", group: "Administration", description: "Open the client demo walkthrough, quotation, and implementation plan." },
  { key: "reports.items.export_pdf", label: "Export items PDF", group: "Reports", description: "Download the items list report as PDF." },
  { key: "reports.items.export_excel", label: "Export items Excel", group: "Reports", description: "Download the items list report as Excel." },
  { key: "users:view", label: "View users", group: "Administration", description: "View user accounts and assignments." },
  { key: "users:create", label: "Create users", group: "Administration", description: "Create user accounts." },
  { key: "users:edit", label: "Edit users", group: "Administration", description: "Update users, assignments, passwords, and status." },
  { key: "users:delete", label: "Delete users", group: "Administration", description: "Delete or archive users." },
  { key: "roles:view", label: "View roles", group: "Administration", description: "View roles and permission assignments." },
  { key: "roles:create", label: "Create roles", group: "Administration", description: "Create new roles from permission checklists." },
  { key: "roles:edit", label: "Edit roles", group: "Administration", description: "Update role permissions and role status." },
  { key: "roles:delete", label: "Delete roles", group: "Administration", description: "Delete roles when no users are assigned." },
  { key: "settings:manage", label: "Manage settings", group: "Administration", description: "Update company settings and setup configuration." },
  { key: "backups:manage", label: "Manage backups", group: "Administration", description: "View, download, and manage backups." },
  { key: "admin:manage", label: "Manage administration", group: "Administration", description: "Compatibility umbrella for all administration tools." },
  { key: "audit:view", label: "View audit", group: "Administration", description: "View audit logs and audit coverage." },
] as const;

export const APP_PERMISSIONS = APP_PERMISSION_DEFINITIONS.map((permission) => permission.key);

export type AppRole = string;
export type AppPermission = (typeof APP_PERMISSION_DEFINITIONS)[number]["key"];

export const permissionsByRole: Record<string, readonly AppPermission[]> = {
  ADMIN: APP_PERMISSIONS,
  SALES: [
    "location:multi",
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:delete",
    "inventory:transfer",
    "inventory:adjust-prices",
    "inventory:manage",
    "sales:create",
    "sales:view",
    "sales:edit",
    "sales:deliveries",
    "sales.receipt.print",
    "sales.receipt.export_pdf",
    "sales.receipt.export_excel",
    "sales.return.create",
    "sales.return.full",
    "sales.return.partial",
    "sales.exchange.create",
    "customer-payments:create",
    "customer-payments:view",
    "purchases:create",
    "purchases:view",
    "purchases:edit",
    "suppliers:view",
    "suppliers:create",
    "suppliers:edit",
    "customers:manage",
    "customers:view",
    "customers:create",
    "customers:edit",
    "suppliers:manage",
    "expenses:view",
    "expenses:create",
    "expenses:edit",
    "accounts:use",
    "accounts:view",
    "sales:manage",
    "reports:view",
    "ai:view",
  ],
  PURCHASE_ROLE: [
    "location:view-all",
    "location:multi",
    "dashboard:view",
    "purchases:create",
    "purchases:view",
    "purchases:edit",
    "suppliers:view",
    "suppliers:create",
    "suppliers:edit",
    "supplier-payments:view",
    "supplier-payments:create",
    "reports:view",
    "ai:view",
    "accounts:use",
    "accounts:view",
  ],
  SALES_ROLE: [
    "location:view-all",
    "location:multi",
    "dashboard:view",
    "sales:create",
    "sales:view",
    "sales:edit",
    "sales:deliveries",
    "sales:manage",
    "sales.receipt.print",
    "sales.receipt.export_pdf",
    "sales.receipt.export_excel",
    "sales.return.create",
    "sales.return.full",
    "sales.return.partial",
    "sales.exchange.create",
    "customers:view",
    "customers:create",
    "customers:edit",
    "customer-payments:view",
    "customer-payments:create",
    "reports:view",
    "ai:view",
    "accounts:use",
    "accounts:view",
  ],
  STORE_ROLE: [
    "location:multi",
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:adjust-prices",
    "inventory:manage",
    "reports:view",
    "ai:view",
  ],
  STORE_STAFF: [
    "location:multi",
    "dashboard:view",
    "inventory:view",
    "inventory:transfer",
    "inventory:manage",
  ],
  MANAGER: [
    "location:view-all",
    "location:multi",
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:adjust-prices",
    "inventory:manage",
    "sales:create",
    "sales:view",
    "sales:edit",
    "sales:deliveries",
    "sales:manage",
    "sales.receipt.print",
    "sales.return.create",
    "customers:view",
    "customers:create",
    "customers:edit",
    "customer-payments:view",
    "customer-payments:create",
    "purchases:create",
    "purchases:view",
    "purchases:edit",
    "suppliers:view",
    "suppliers:create",
    "suppliers:edit",
    "supplier-payments:view",
    "supplier-payments:create",
    "expenses:view",
    "expenses:create",
    "accounts:use",
    "accounts:view",
    "accounts:manage",
    "cheques:view",
    "ledger:view",
    "cash-transfers:view",
    "reports:view",
    "ai:view",
    "audit:view",
    "demo:view",
  ],
  WAREHOUSE_ROLE: [
    "location:multi",
    "dashboard:view",
    "inventory:view",
    "inventory:transfer",
    "inventory:manage",
    "purchases:create",
    "purchases:view",
    "suppliers:view",
    "reports:view",
    "ai:view",
  ],
  FINANCE_ROLE: [
    "location:view-all",
    "location:multi",
    "dashboard:view",
    "customers:view",
    "customer-payments:view",
    "customer-payments:create",
    "suppliers:view",
    "supplier-payments:view",
    "supplier-payments:create",
    "purchases:view",
    "sales:view",
    "expenses:view",
    "expenses:create",
    "expenses:edit",
    "accounts:use",
    "accounts:view",
    "accounts:create",
    "accounts:edit",
    "accounts:manage",
    "cheques:view",
    "cheques:manage",
    "ledger:view",
    "cash-transfers:view",
    "cash-transfers:create",
    "cash-transfers:manage",
    "reports:view",
    "ai:view",
    "audit:view",
  ],
};

const permissionImplications: Partial<Record<AppPermission, readonly AppPermission[]>> = {
  "inventory:manage": ["inventory:view", "inventory:create", "inventory:edit", "inventory:delete", "inventory:transfer", "inventory:adjust-prices"],
  "sales:manage": ["sales:view", "sales:edit", "sales:delete", "sales:deliveries"],
  "customers:manage": ["customers:view", "customers:create", "customers:edit", "customers:delete"],
  "suppliers:manage": ["suppliers:view", "suppliers:create", "suppliers:edit", "suppliers:delete"],
  "accounts:manage": ["accounts:view", "accounts:create", "accounts:edit", "accounts:delete", "accounts:use", "cheques:view", "cheques:manage", "supplier-payments:view", "supplier-payments:create"],
  "cash-transfers:manage": ["cash-transfers:view", "cash-transfers:create"],
  "admin:manage": ["users:view", "users:create", "users:edit", "users:delete", "roles:view", "roles:create", "roles:edit", "roles:delete", "settings:manage", "backups:manage", "audit:view", "demo:view"],
};

const pathPermissionRules: ReadonlyArray<{
  prefix: string;
  permission: AppPermission;
}> = [
  { prefix: "/admin/users", permission: "users:view" },
  { prefix: "/admin/locations", permission: "settings:manage" },
  { prefix: "/setup", permission: "settings:manage" },
  { prefix: "/admin/roles", permission: "roles:view" },
  { prefix: "/admin/backups", permission: "backups:manage" },
  { prefix: "/admin/settings", permission: "settings:manage" },
  { prefix: "/admin/audit", permission: "audit:view" },
  { prefix: "/admin", permission: "admin:manage" },
  { prefix: "/demo", permission: "demo:view" },
  { prefix: "/assistant", permission: "ai:view" },
  { prefix: "/reports", permission: "reports:view" },
  { prefix: "/finance/cheques", permission: "cheques:view" },
  { prefix: "/finance/expenses", permission: "expenses:view" },
  { prefix: "/finance/accounts", permission: "accounts:view" },
  { prefix: "/finance/cash-transfers", permission: "cash-transfers:view" },
  { prefix: "/finance/cash", permission: "cash-transfers:view" },
  { prefix: "/finance/ledger", permission: "ledger:view" },
  { prefix: "/purchases/new", permission: "purchases:create" },
  { prefix: "/purchases/suppliers", permission: "suppliers:view" },
  { prefix: "/purchases/supplier-payments", permission: "supplier-payments:view" },
  { prefix: "/purchases/imports", permission: "purchases:view" },
  { prefix: "/purchases", permission: "purchases:view" },
  { prefix: "/sales/pos", permission: "sales:create" },
  { prefix: "/sales/wholesale", permission: "sales:create" },
  { prefix: "/sales/new", permission: "sales:create" },
  { prefix: "/sales/agents", permission: "customers:view" },
  { prefix: "/sales/customers", permission: "customers:view" },
  { prefix: "/sales/customer-credit", permission: "customers:view" },
  { prefix: "/sales/customer-payments", permission: "customer-payments:create" },
  { prefix: "/sales", permission: "sales:view" },
  { prefix: "/inventory/products", permission: "inventory:edit" },
  { prefix: "/inventory/transfers", permission: "inventory:transfer" },
  { prefix: "/inventory/stock", permission: "inventory:view" },
  { prefix: "/inventory/low-stock", permission: "inventory:view" },
  { prefix: "/inventory/out-of-stock", permission: "inventory:view" },
  { prefix: "/inventory/alert-records", permission: "inventory:view" },
  { prefix: "/inventory/stock-movements", permission: "inventory:view" },
  { prefix: "/inventory", permission: "inventory:view" },
  { prefix: "/dashboard", permission: "dashboard:view" },
  { prefix: "/profile", permission: "dashboard:view" },
];

export function hasPermission(
  role: AppRole,
  permission: AppPermission,
  grantedPermissions?: readonly string[],
) {
  if (role === "ADMIN") return true;
  const rolePermissions = grantedPermissions ?? permissionsByRole[role] ?? [];
  if (rolePermissions.includes(permission)) return true;

  return rolePermissions.some((grantedPermission) => {
    const impliedPermissions = permissionImplications[grantedPermission as AppPermission] ?? [];
    return impliedPermissions.includes(permission);
  });
}

export function getRequiredPermissionForPath(pathname: string) {
  const match = pathPermissionRules.find(
    (rule) => pathname === rule.prefix || pathname.startsWith(`${rule.prefix}/`),
  );

  return match?.permission ?? null;
}

export function canAccessPath(
  role: AppRole,
  pathname: string,
  grantedPermissions?: readonly string[],
) {
  const requiredPermission = getRequiredPermissionForPath(pathname);

  return !requiredPermission || hasPermission(role, requiredPermission, grant